#!/usr/bin/env bash
matlab="/Applications/MATLAB_R2016a.app/bin/matlab"
julia="/Applications/JuliaPro-0.6.3.1.app/Contents/Resources/julia/Contents/Resources/julia/bin/julia"
echo "Multitask Learning Pipeline"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Setting up data using MATLAB"
$matlab -nodisplay -nosplash -nodesktop -r "run('Th17example_setup.m');exit;"
echo "Setup file names output to setup.txt"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Creating networks using multitask learning in Julia"
$julia "./Th17example_inference.jl"
